test: Transition W3C trace-context test to vanilla PHP

diff --git a/tests/TraceContext/W3CTestService/symfony-setup b/tests/TraceContext/W3CTestService/symfony-setup
--- a/tests/TraceContext/W3CTestService/symfony-setup
+++ b/tests/TraceContext/W3CTestService/symfony-setup
@@ -1,50 +1,29 @@
 #!/usr/bin/env bash
 set -x
 
-git config --global user.email "otel@open-telemetry.example.com"
+function install_symfony() {
+    curl -sS https://get.symfony.com/cli/installer | bash
+    mv /root/.symfony/bin/symfony /usr/local/bin/symfony
+}
 
-# Install Symfony
-curl -sS https://get.symfony.com/cli/installer | bash
-mv /root/.symfony/bin/symfony /usr/local/bin/symfony
+cd "tests/TraceContext/W3CTestService" || { echo "error: could not cd into the W3CTestService directory."; exit 1; }
 
-# Set up Symfony test application
-cd tests/TraceContext/W3CTestService || { printf "Something went wrong: could not cd into W3CTestService directory."; exit 1; }
-rm -rf test_app
-symfony new test_app --version=5.2
+# Install Symfony: we will use the Symfony server as the built-in PHP server doesn't play well with duplicate headers
+install_symfony
+if [[ $? -ne 6 ]] # retry if we fail to install (flake)
+then
+    install_symfony
+fi
 
-# Move our files into the test application
-cp index.php test_app/public/index.php
-cp TestController.php test_app/src/Controller/TestController.php
-
-cd test_app || { printf "Something went wrong: could not cd into test_app."; exit 1; }
-
-# Link the local opentelemetry changes to vendor/open-telemetry
-composer config repositories.local \
-    '{"type": "path", "url": "/usr/src/open-telemetry/", "options": {"symLink": true }}' \
-    --file composer.json
-composer config minimum-stability dev --file composer.json
-
-composer require symfony/http-client
-composer require annotations
-composer require nyholm/psr7 "*"
-composer require open-telemetry/opentelemetry "*"
-composer require php-http/mock-client "*"
-
-rm composer.lock
-composer clearcache
-composer install
-
-# Start the server to start listening in the background
+# Start the test service in the background
 symfony server:start -d --port=8001 --no-tls
 
-# Setup the TraceContext Test Service
+# Setup dependencies for the trace-context test
 apk add --no-cache py3-pip py3-aiohttp
 
-cd ..
+# Fetch the latest trace-context tests
 rm -rf trace-context
 git clone https://github.com/w3c/trace-context.git
 
-cd trace-context/test || { printf "Failed to cd to trace-context/test" ; exit; }
-
 # Run the test
-python3 test.py http://127.0.0.1:8001/test
+python3 "trace-context/test/test.py" http://127.0.0.1:8001/test
